Env: dev
ApplicationName: app3
vm-windows:
  vm32:
    azure_region: westeurope
    organization-code: sie
    subscription-code: lan1
    environment-code: t
    rg_location: West Europe
    vnet_name: sie-lz1-d-rsg-acp-vnet
    subnet_name: default
    rg_name: sie-lz1-d-rsg-acp
    vm_size: Standard_DS1_v2
    tags:
      User_id: A827884
      User_email: Jason@atos.net
      Dapartment: CES
      AtosManaged: 'true'